# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  star_castle_config = debug

else ifeq ($(config),release)
  star_castle_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := star-castle

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

star-castle:
ifneq (,$(star_castle_config))
	@echo "==== Building star-castle ($(star_castle_config)) ===="
	@${MAKE} --no-print-directory -C . -f star-castle.make config=$(star_castle_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f star-castle.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   star-castle"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"